name: Run Tests Action
description: "Runs the test suite for the project."
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Run Tests
      shell: bash
      run: |
        echo "Running tests..."