name: Check Versions and Run Tests
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - dev
      - main

jobs:
  validate-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Version Check
        uses: ./.github/actions/version-check
        with:
          base-sha: ${{ github.event.pull_request.base.sha }}

      - name: Run Tests
        uses: ./.github/actions/run-tests
